language: python

install:
  - pip install -r requirements.txt

before_script:
  - npm install
  - git submodule update --init

script:
  #- python parser.py
  #- node_modules/csv-test/bin/csv-test tests/csv-test-config.yml '2014/*' tests/csv-test-validators.yml
  #- node_modules/csv-test/bin/csv-test tests/csv-test-config.yml '2015/*' tests/csv-test-validators.yml
  - cd tests
  - behave
