language: python

install:
  - pip install -r requirements.txt

before_script:
  - npm install
  - git submodule update --init

script:
  - python parser.py
  - node_modules/csv-test/bin/csv-test csv-test-config.yml '2014/*' csv-test-validators.yml
  - node_modules/csv-test/bin/csv-test csv-test-config.yml '2015/*' csv-test-validators.yml
