language: python

before_script:
  - npm install
  - git submodule update --init

script:
  python parser.py
  node_modules/csv-test/bin/csv-test csv-test-config.yml 2014/20141104__wi__general_ward.csv csv-test-validators.yml
