language: python

install:
  - pip install -r requirements.txt

before_script:
  - npm install
  - git submodule update --init

script:
  - python parser.py
  - node_modules/csv-test/bin/csv-test csv-test-config.yml 2014/20141104__wi__general_ward.csv csv-test-validators.yml
  - node_modules/csv-test/bin/csv-test csv-test-config.yml 2015/20150721__wi__general_ward.csv csv-test-validators.yml
  - node_modules/csv-test/bin/csv-test csv-test-config.yml 2015/20150929__wi__general_ward.csv csv-test-validators.yml
  - node_modules/csv-test/bin/csv-test csv-test-config.yml 2015/20150623__wi__primary_ward.csv csv-test-validators.yml
  - node_modules/csv-test/bin/csv-test csv-test-config.yml 2015/20150901__wi__primary_ward.csv csv-test-validators.yml
